version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.staging
    command: nginx
    hostname: "netguru.merck-react.staging.web"
    labels:
      - "netguru.appname=merck-react"
      - "netguru.stage=staging"
    env_file: /home/deploy/apps/merck-react/shared/secrets.env
    environment:
      - VIRTUAL_HOST=merck-react.staging.devguru.co
      - VIRTUAL_PORT=3000
    expose:
      - 3000
    networks:
      - frontend

networks:
  frontend:
    external:
      name: frontend
