import COLORS from '~/utils/consts/colors'

export const DEFAULT_COLORS = [
  COLORS.VIBRANT_GREEN,
  COLORS.VIBRANT_MAGENTA,
  COLORS.VIBRANT_CYAN,
  COLORS.VIBRANT_YELLOW,
  COLORS.RICH_PURPLE,
  COLORS.RICH_BLUE,
  COLORS.RICH_GREEN,
]

export const BARS_WRAPPER_HEIGHT = 244

export const TICKS_OFFSET = 35
export const TICKS_PADDING = 50
export const TICKS_LINE_HEIGHT = 16
